config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "It already exists!" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create, :destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @list = List.find(params[:id])
    # should be? @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, placeholder: "something that i want to tell the user" %>
  <%= f.association :movie, prompt: "Movie, please", input_html: {class: "select2"} %>
  <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h2>Lists of Movies:</h2>

  <tbody>

<!-- for face detection -->
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg" %>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name%></td>
        <td><%= link_to 'Look at List', list_path(list) %></td>
      </tr>
    <% end %>
    <div>
      <%= link_to 'Create new List', new_list_path, class: 'btn btn-danger'%>
    </div>
  </tbody>

<%= cl_image_tag("dkcpoy7f5namtvtzsjyv",
      width: 400, height: 300, crop: :fill) %>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-danger' %>
  </div>
<% end %>

 <%= link_to "cancel", lists_path(@list) %>

app/views/lists/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @list.name %>

  <%= link_to 'add a movie', new_list_bookmark_path(@list), class: 'btn btn-flat' %>
  <%= link_to 'detete this list', list_path(@list), method: :delete, class: 'btn btn-cancel', data: { confirm: 'Are you sure you want to delete this list?' } %>
  <%= link_to "go back", lists_path(@list) %>

 <div>
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div>
        <div>
          <%= movie.title %>
          <%= movie.overview %>
          <%= bookmark.comment %>
        </div>
        <%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: { confirm: "Remove #{movie.title} from #{@list.name} list?"} %>
      </div>
    <% end %>
  </div>
</p>